### ISSUE TITLE
Better input system

### ISSUE THREAD

**Issue by panthavma** [panthavma/castagne#4]
Improve the input parsing code : 
- Allow user-defined buttons
- Add buffers
- Rebinding Menu

**Comment by TheYellowArchitect** [comment]
I would like to add a minor suggestion, for the rebinding menu, to be able to accept combined buttons and hence act as a macro
E.g. RB=Up+A

**Comment by panthavma** [comment]
Hi! You mean for the players or the developers to be able to define those macros?

**Comment by panthavma** [comment]
Buffer added in #45
