### ISSUE TITLE
Node Problems (I am a novice in code, but great in design)

### ISSUE THREAD

**Issue by SonataAvalon** [panthavma/castagne#56]
![Screen Shot 2024-01-30 at 10 49 23 AM](https://github.com/panthavma/castagne/assets/77213194/8b456b80-d876-4dfe-b4b9-d31942eaa092)

This happened after I changed the text of the words to something different.  
Is there something I can do to fix this problem? And where could this fix be applied, I do not know code except limited knowledge of HTML.

I can only guess it's trying to pull from a node that doesn't exist in the directory.

**Comment by SonataAvalon** [comment]
This still happens after I tried to change the names back to their original status as well.

**Comment by panthavma** [comment]
Hey! Just saw that
Yes, the CastagneStarter is very sensitive to names as it also goes behind it. In theory you shouldn't need to alter this file anyway, as it only launches the engine.

(I'm leaving the issue open for now so you can answer, but for support like this the "discussion" tab is a better point of contact :) )

**Comment by SonataAvalon** [comment]
Thank you for responding, man! 
I had a feeling this was the case!
